# Generated by Django 6.1.1 on 2026-09-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, unique=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
